services:
  voice-chat-bot:
    image: freakynoblegas/voice-chat-bot:1.0
    pull_policy: build
    build: .
    container_name: voice-chat-bot
    restart: unless-stopped
    env_file:
      - ../.env